# -*- coding: utf-8 -*-
"""Copy of milestone2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IzNtsTG_dZjPRbrVQ0YTJEx0bhXVx2s2
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/GKSJ-AI-CliniScan/HealthForecastAI.git
# %cd HealthForecastAI
!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/HealthForecastAI/ml
!ls

!find . -name "*.pkl"

!pip install xgboost pyyaml scikit-learn joblib -q

from src.utils.config import load_config
config = load_config("configs/config.yaml")
print(config)

print(config["dataset"]["raw_path"])

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/HealthForecastAI
!git branch -a

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/HealthForecastAI/ml

!ls artifacts

from google.colab import files
uploaded = files.upload()

!mv diabetic_data.csv data/raw/

!ls data/raw

!pip install xgboost pyyaml scikit-learn joblib -q
!python -m src.models.train --config configs/config.yaml

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/HealthForecastAI
!python -m ml.src.models.train --config ml/configs/config.yaml

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/HealthForecastAI/ml

!mkdir -p ml/data/raw
!cp data/raw/diabetic_data.csv ml/data/raw/diabetic_data.csv
!ls ml/data/raw

!python -m src.models.train --config configs/config.yam-l

!find . -name "*.joblib"

pipeline = joblib.load("./ml/artifacts/readmission_model.joblib")

from src.data.load_data import load_raw, binarise_target
from src.data.preprocess import basic_clean
from src.features.build_features import add_utilisation_features
from src.utils.config import load_config

config = load_config("configs/config.yaml")
frame = load_raw("ml/data/raw/diabetic_data.csv")
frame = basic_clean(frame, config)
frame = add_utilisation_features(frame)

target = binarise_target(frame[config["dataset"]["target_column"]], config["dataset"]["positive_label"])
features = frame.drop(columns=[config["dataset"]["target_column"]])

print(features.shape)

risk_scores = pipeline.predict_proba(features)[:, 1]
results = features.copy()
results["risk_score"] = risk_scores
results.head()

def assign_risk_level(score):
    if score >= 0.7:
        return "High"
    elif score >= 0.4:
        return "Medium"
    else:
        return "Low"

results["risk_level"] = results["risk_score"].apply(assign_risk_level)
results["risk_level"].value_counts()

def clinical_insight(risk_level):
    if risk_level == "High":
        return "Recommend intensive follow-up within 7 days, medication review, care coordinator assigned."
    elif risk_level == "Medium":
        return "Recommend standard follow-up within 14-30 days, monitor symptoms."
    else:
        return "Low risk: routine discharge instructions sufficient."

results["clinical_recommendation"] = results["risk_level"].apply(clinical_insight)
results[["risk_score", "risk_level", "clinical_recommendation"]].head(10)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))
sns.histplot(results["risk_score"], bins=30, color="#4C72B0", kde=True)
plt.title("Distribution of Patient Risk Scores")
plt.xlabel("Predicted Risk Score")
plt.ylabel("Number of Patients")
plt.show()

ax = results["risk_level"].value_counts().reindex(["Low","Medium","High"]).plot(
    kind="bar", color=["#55A868","#DD8452","#C44E52"]
)
ax.set_title("Patients by Risk Level")
plt.xticks(rotation=0)
plt.show()





