# -*- coding: utf-8 -*-
"""Copy of  milestone3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11I_Cvl2q6l6PNgQB5bxjfiHsVoXLaiqp
"""

risk_scores = pipeline.predict_proba(features)[:, 1]
results = features.copy()
results["risk_score"] = risk_scores
results.head()

def assign_risk_level(score):
    if score >= 0.7:
        return "High"
    elif score >= 0.4:
        return "Medium"
    else:
        return "Low"

results["risk_level"] = results["risk_score"].apply(assign_risk_level)
results["risk_level"].value_counts()

def clinical_insight(risk_level):
    if risk_level == "High":
        return "Recommend intensive follow-up within 7 days, medication review, care coordinator assigned."
    elif risk_level == "Medium":
        return "Recommend standard follow-up within 14-30 days, monitor symptoms."
    else:
        return "Low risk: routine discharge instructions sufficient."

results["clinical_recommendation"] = results["risk_level"].apply(clinical_insight)
results[["risk_score", "risk_level", "clinical_recommendation"]].head(10)

# frame still has human-readable columns (before encoding happens inside
# the pipeline), so we attach risk outputs to it for analysis
analysis_df = frame.copy()
analysis_df["risk_score"] = results["risk_score"].values
analysis_df["risk_level"] = results["risk_level"].values

treatment_eval = analysis_df.groupby("change")[config["dataset"]["target_column"]].value_counts(normalize=True).unstack()
print("Readmission rate by medication change status:")
treatment_eval

recovery_summary = analysis_df.groupby("risk_level")["time_in_hospital"].agg(
    avg_stay="mean", median_stay="median", max_stay="max"
).reindex(["Low", "Medium", "High"])

print("Recovery / hospital stay summary by risk level:")
recovery_summary

med_effectiveness = analysis_df.groupby("diabetesMed")[config["dataset"]["target_column"]].value_counts(normalize=True).unstack()
print("Readmission rate by diabetes medication status:")
med_effectiveness

performance_dashboard = {
    "total_patients": len(analysis_df),
    "avg_risk_score": analysis_df["risk_score"].mean(),
    "high_risk_pct": (analysis_df["risk_level"] == "High").mean() * 100,
    "avg_time_in_hospital": analysis_df["time_in_hospital"].mean(),
    "avg_medications": analysis_df["num_medications"].mean(),
    "readmission_rate_30d": (analysis_df[config["dataset"]["target_column"]] == "<30").mean() * 100,
}

print("Healthcare Performance Dashboard:")
for k, v in performance_dashboard.items():
    print(f"  {k}: {v:.2f}" if isinstance(v, float) else f"  {k}: {v}")

outcome_by_age = analysis_df.groupby("age")["risk_level"].value_counts(normalize=True).unstack().reindex(
    ["[0-10)","[10-20)","[20-30)","[30-40)","[40-50)","[50-60)","[60-70)","[70-80)","[80-90)","[90-100)"]
)

print("Risk level distribution by age group:")
outcome_by_age

plt.figure(figsize=(8, 5))
sns.boxplot(data=analysis_df, x="risk_level", y="time_in_hospital", order=["Low", "Medium", "High"], palette="Set2")
plt.title("Hospital Stay Length by Risk Level")
plt.xlabel("Risk Level")
plt.ylabel("Time in Hospital (days)")
plt.show()

import pandas as pd

med_bins = pd.cut(analysis_df["num_medications"], bins=[0, 10, 20, 30, 100])
trend = analysis_df.groupby(med_bins)[config["dataset"]["target_column"]].apply(
    lambda x: (x == "<30").mean() * 100
)

plt.figure(figsize=(8, 5))
trend.plot(kind="line", marker="o", color="#C44E52")
plt.title("30-Day Readmission Rate by Medication Count")
plt.xlabel("Number of Medications (binned)")
plt.ylabel("Readmission Rate (%)")
plt.show()



report_cols = ["risk_score", "risk_level", "time_in_hospital", "num_medications",
               "diabetesMed", "change", config["dataset"]["target_column"]]

analysis_df[report_cols].to_csv("healthcare_analytics_report.csv", index=False)
print("Saved healthcare_analytics_report.csv")