version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb+srv://padharthidhanalakshmi_db_user:12ikStIgljXUNJa0@cluster0.wnx5exe.mongodb.net/?appName=Cluster0
      - DATABASE_NAME=HealthForecastAI
      - SECRET_KEY=healthforecast_ai_secret_key_super_secure_jwt_2026
      - ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: always
