"""Render a ReportDocument as CSV, Excel or PDF bytes.

The exporters only lay out data they are given - every figure is computed
upstream by the analytics services - so the three formats can never disagree.
"""

import csv
import io
import re
from collections.abc import Callable
from dataclasses import dataclass, field
from datetime import datetime

from fpdf import FPDF
from fpdf.fonts import FontFace
from openpyxl import Workbook
from openpyxl.cell.cell import ILLEGAL_CHARACTERS_RE
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from app.utils.formula_safety import neutralise_formula

Cell = str | int | float | None


@dataclass(frozen=True)
class ReportTable:
    """One titled table of a report."""

    title: str
    columns: list[str]
    rows: list[list[Cell]]


@dataclass(frozen=True)
class ReportDocument:
    """Format-independent report content."""

    title: str
    generated_at: datetime
    generated_by: str
    filters: dict[str, str]
    summary: list[tuple[str, Cell]]
    tables: list[ReportTable] = field(default_factory=list)

    def header_lines(self) -> list[tuple[str, str]]:
        applied = ", ".join(f"{k}={v}" for k, v in sorted(self.filters.items())) or "none"
        return [
            ("Report", self.title),
            ("Generated at (UTC)", self.generated_at.strftime("%Y-%m-%d %H:%M:%S")),
            ("Generated by", self.generated_by),
            ("Filters", applied),
        ]


# --------------------------------------------------------------------------
# CSV
# --------------------------------------------------------------------------


def _csv_cell(value: Cell) -> Cell:
    if value is None:
        return ""
    if isinstance(value, str):
        return neutralise_formula(value)
    return value


def to_csv(document: ReportDocument) -> bytes:
    """UTF-8 CSV: header block, summary, then each table separated by a blank row."""
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    for label, value in document.header_lines():
        writer.writerow([_csv_cell(label), _csv_cell(value)])
    writer.writerow([])
    writer.writerow(["Summary"])
    writer.writerow(["Metric", "Value"])
    for label, summary_value in document.summary:
        writer.writerow([_csv_cell(label), _csv_cell(summary_value)])
    for table in document.tables:
        writer.writerow([])
        writer.writerow([_csv_cell(table.title)])
        writer.writerow([_csv_cell(column) for column in table.columns])
        for row in table.rows:
            writer.writerow([_csv_cell(cell) for cell in row])
    return buffer.getvalue().encode("utf-8")


# --------------------------------------------------------------------------
# Excel
# --------------------------------------------------------------------------

_HEADER_FONT = Font(bold=True, color="FFFFFF")
_HEADER_FILL = PatternFill("solid", fgColor="1F4E78")
_SHEET_NAME_INVALID = re.compile(r"[\[\]:*?/\\]")


def _xlsx_cell(value: Cell) -> Cell:
    if isinstance(value, str):
        return neutralise_formula(ILLEGAL_CHARACTERS_RE.sub("", value))
    return value


def _sheet_name(title: str, taken: set[str]) -> str:
    base = _SHEET_NAME_INVALID.sub(" ", title).strip()[:31] or "Sheet"
    name, suffix = base, 2
    while name.lower() in taken:
        tail = f" ({suffix})"
        name = base[: 31 - len(tail)] + tail
        suffix += 1
    taken.add(name.lower())
    return name


def _write_header_row(sheet, row_index: int, columns: list[str]) -> None:  # type: ignore[no-untyped-def]
    for column_index, column in enumerate(columns, start=1):
        cell = sheet.cell(row=row_index, column=column_index, value=_xlsx_cell(column))
        cell.font = _HEADER_FONT
        cell.fill = _HEADER_FILL
        cell.alignment = Alignment(vertical="center")


def _autosize(sheet) -> None:  # type: ignore[no-untyped-def]
    widths: dict[int, int] = {}
    for row in sheet.iter_rows():
        for cell in row:
            if cell.value is not None:
                widths[cell.column] = max(widths.get(cell.column, 0), len(str(cell.value)))
    for column_index, width in widths.items():
        sheet.column_dimensions[get_column_letter(column_index)].width = min(width + 2, 60)


def to_xlsx(document: ReportDocument) -> bytes:
    """Workbook with a Summary sheet plus one sheet per table. Numbers stay numeric."""
    workbook = Workbook()
    taken: set[str] = set()

    summary = workbook.active
    assert summary is not None
    summary.title = _sheet_name("Summary", taken)
    summary.cell(row=1, column=1, value=_xlsx_cell(document.title)).font = Font(bold=True, size=14)
    row_index = 3
    for label, value in document.header_lines()[1:]:
        summary.cell(row=row_index, column=1, value=_xlsx_cell(label)).font = Font(bold=True)
        summary.cell(row=row_index, column=2, value=_xlsx_cell(value))
        row_index += 1
    row_index += 1
    _write_header_row(summary, row_index, ["Metric", "Value"])
    for label, summary_value in document.summary:
        row_index += 1
        summary.cell(row=row_index, column=1, value=_xlsx_cell(label))
        summary.cell(row=row_index, column=2, value=_xlsx_cell(summary_value))
    _autosize(summary)

    for table in document.tables:
        sheet = workbook.create_sheet(_sheet_name(table.title, taken))
        _write_header_row(sheet, 1, table.columns)
        for row in table.rows:
            sheet.append([_xlsx_cell(cell) for cell in row])
        sheet.freeze_panes = "A2"
        _autosize(sheet)

    buffer = io.BytesIO()
    workbook.save(buffer)
    return buffer.getvalue()


# --------------------------------------------------------------------------
# PDF
# --------------------------------------------------------------------------


def _pdf_text(value: Cell) -> str:
    """Core PDF fonts are Latin-1 only; anything else is replaced, not a crash."""
    if value is None:
        text = "-"
    elif isinstance(value, float):
        text = f"{value:.4f}"
    else:
        text = str(value)
    return text.encode("latin-1", "replace").decode("latin-1")


class _ReportPDF(FPDF):
    def __init__(self, title: str) -> None:
        super().__init__(orientation="P", unit="mm", format="A4")
        self.report_title = _pdf_text(title)
        self.set_title(self.report_title)
        self.set_author("HealthForecast AI")
        self.set_auto_page_break(auto=True, margin=15)
        self.alias_nb_pages()

    def footer(self) -> None:
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(110, 110, 110)
        self.cell(0, 8, f"HealthForecast AI - {self.report_title}", align="L")
        self.cell(0, 8, f"Page {self.page_no()}/{{nb}}", align="R")


def _pdf_table(pdf: FPDF, columns: list[str], rows: list[list[Cell]]) -> None:
    pdf.set_font("Helvetica", "", 9)
    heading = FontFace(emphasis="BOLD", color=(255, 255, 255), fill_color=(31, 78, 120))
    with pdf.table(
        headings_style=heading,
        line_height=6,
        text_align="LEFT",
        cell_fill_color=(242, 242, 242),
        cell_fill_mode="ROWS",
    ) as table:
        header = table.row()
        for column in columns:
            header.cell(_pdf_text(column))
        for values in rows:
            row = table.row()
            for value in values:
                row.cell(_pdf_text(value))


def to_pdf(document: ReportDocument) -> bytes:
    """A4 report: title, generation metadata, summary table, then each data table."""
    pdf = _ReportPDF(document.title)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(31, 78, 120)
    pdf.cell(0, 12, _pdf_text(document.title), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 9)
    for label, value in document.header_lines()[1:]:
        pdf.multi_cell(0, 5, _pdf_text(f"{label}: {value}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "Summary", new_x="LMARGIN", new_y="NEXT")
    _pdf_table(pdf, ["Metric", "Value"], [[label, value] for label, value in document.summary])

    for table in document.tables:
        pdf.ln(6)
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 8, _pdf_text(table.title), new_x="LMARGIN", new_y="NEXT")
        if table.rows:
            _pdf_table(pdf, table.columns, table.rows)
        else:
            pdf.set_font("Helvetica", "I", 9)
            pdf.cell(0, 6, "No data for the selected filters.", new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())


EXPORTERS: dict[str, Callable[[ReportDocument], bytes]] = {
    "csv": to_csv,
    "xlsx": to_xlsx,
    "pdf": to_pdf,
}

MEDIA_TYPES: dict[str, str] = {
    "csv": "text/csv; charset=utf-8",
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "pdf": "application/pdf",
}
