import { PatientClinicalSupportSummary } from '@/types/clinicalSupport';

export const MOCK_CLINICAL_DOSSIERS: Record<number, PatientClinicalSupportSummary> = {
  1: {
    patient_id: 1,
    patient_name: 'Eleanor Vance',
    medical_record_number: 'MRN-10029',
    age_group: '65-74',
    gender: 'Female',
    department: 'Endocrinology / Internal Medicine',
    primary_diagnosis: 'Type 2 Diabetes Mellitus with Hyperglycemia & Stage 3b CKD',
    admission_status: 'admitted',
    risk_category: 'high',
    readmission_probability: 0.84,
    follow_up_days: 3,
    recommendations: [
      {
        id: 'rec-1-1',
        title: 'Intensive Basal-Bolus Insulin Optimization + CGM Placement',
        category: 'medication',
        priority: 'critical',
        suggested_timeframe: 'Within 24 hours',
        rationale:
          'Admission HbA1c 9.8% with fluctuating postprandial glucose peaks > 250 mg/dL indicates failing oral monotherapy.',
        protocol_action:
          'Initiate endocrinology-guided basal-bolus titration protocol and attach continuous glucose monitoring sensor.',
        status: 'accepted',
      },
      {
        id: 'rec-1-2',
        title: 'Renal-Dosed Medication Reconciliation & SGLT2i Transition',
        category: 'pharmacological' as unknown as 'medication',
        priority: 'high',
        suggested_timeframe: 'Prior to discharge',
        rationale:
          'eGFR 42 mL/min/1.73m² requires dose moderation of metformin and evaluation for renal-protective SGLT2 inhibitor.',
        protocol_action:
          'Order clinical pharmacy consult for drug-drug interaction audit across all 18 active home medications.',
        status: 'pending',
      },
      {
        id: 'rec-1-3',
        title: 'Post-Discharge Tele-Care & Remote Biometric Enrollment',
        category: 'monitoring',
        priority: 'high',
        suggested_timeframe: 'At discharge',
        rationale:
          'Patient has 2 prior emergency admissions within 12 months, placing her in the 84th percentile for 30-day readmission risk.',
        protocol_action:
          'Enroll patient in the 30-Day Virtual Care Transition Pathway with cellular blood glucose meter and daily nurse check-ins.',
        status: 'pending',
      },
      {
        id: 'rec-1-4',
        title: 'Diabetic Foot Examination & Podiatry Referral',
        category: 'specialist_referral',
        priority: 'medium',
        suggested_timeframe: 'Within 14 days post-discharge',
        rationale:
          'Reported mild peripheral neuropathy in bilateral lower extremities with reduced sensation.',
        protocol_action:
          'Schedule outpatient comprehensive diabetic foot screen and patient education session.',
        status: 'pending',
      },
    ],
    risk_drivers: [
      {
        id: 'rd-1-1',
        driver_name: 'Severe Glycemic Instability',
        category: 'physiological',
        impact: 'high',
        patient_value: 'HbA1c 9.8% (Glucose 242 mg/dL)',
        benchmark_value: '< 7.0% (100-140 mg/dL)',
        clinical_significance:
          'Uncontrolled hyperglycemia promotes vascular inflammation, impairs immune response, and drastically increases acute decompensation.',
        contribution_percent: 32,
      },
      {
        id: 'rd-1-2',
        driver_name: 'Extreme Polypharmacy Complexity',
        category: 'pharmacological',
        impact: 'high',
        patient_value: '18 Active Prescriptions',
        benchmark_value: '< 8 Formularies',
        clinical_significance:
          'Exponentially elevates risk of drug-drug interactions, unintended duplication, and patient compliance breakdown post-discharge.',
        contribution_percent: 26,
      },
      {
        id: 'rd-1-3',
        driver_name: 'Prior Recurrent Acute Utilization',
        category: 'utilization',
        impact: 'high',
        patient_value: '2 Inpatient & 1 ER Visit in 12m',
        benchmark_value: '0 Recent Admissions',
        clinical_significance:
          'Historical acute utilization is the single strongest epidemiological marker for 30-day post-discharge readmission.',
        contribution_percent: 22,
      },
      {
        id: 'rd-1-4',
        driver_name: 'Compromised Renal Clearance',
        category: 'clinical',
        impact: 'medium',
        patient_value: 'eGFR 42 mL/min (CKD 3b)',
        benchmark_value: '> 60 mL/min/1.73m²',
        clinical_significance:
          'Limits safe pharmacological dosing windows and elevates risk of hypoglycemia from prolonged drug half-lives.',
        contribution_percent: 20,
      },
    ],
    discharge_plan: {
      patient_id: 1,
      ready_for_discharge: false,
      readiness_score: 58,
      target_discharge_date: 'In 48-72 hours (Pending Glycemic Stability)',
      discharge_readiness_summary:
        'Patient remains in inpatient glycemic titration phase. Discharge is contraindicated until fasting glucose remains under 160 mg/dL for 24 continuous hours and medication teach-back is completed.',
      criteria: [
        {
          id: 'crit-1-1',
          label: 'Vital Signs Hemodynamic Stability (>24h afebrile)',
          category: 'vital_signs',
          is_met: true,
          recorded_value: 'BP 126/78, HR 68, Temp 98.4°F',
          required_target: 'Normotensive, afebrile 24h',
        },
        {
          id: 'crit-1-2',
          label: 'Fasting Blood Glucose Stabilization',
          category: 'lab_stability',
          is_met: false,
          recorded_value: 'Fasting BG: 184 mg/dL',
          required_target: '100 - 150 mg/dL consistently',
        },
        {
          id: 'crit-1-3',
          label: 'Clinical Pharmacist Medication Reconciliation',
          category: 'medication_reconciliation',
          is_met: false,
          recorded_value: 'Pending final review',
          required_target: 'Completed with printed schedule',
        },
        {
          id: 'crit-1-4',
          label: 'Independent Mobility & Functional ADL Assessment',
          category: 'mobility_adl',
          is_met: true,
          recorded_value: 'Ambulates 150ft with walker',
          required_target: 'Safe unassisted transfers',
        },
        {
          id: 'crit-1-5',
          label: 'Caregiver Support & Transportation Confirmed',
          category: 'social_support',
          is_met: true,
          recorded_value: 'Daughter confirmed pickup',
          required_target: 'Confirmed post-discharge caregiver',
        },
      ],
      risk_mitigation: [
        {
          id: 'mit-1-1',
          action: 'Complete clinical pharmacist bedside medication reconciliation and patient teach-back',
          responsible_role: 'Clinical Pharmacist',
          priority: 'high',
          completed: false,
        },
        {
          id: 'mit-1-2',
          action: 'Verify activation of cellular blood glucose meter for remote tele-monitoring team',
          responsible_role: 'Virtual Care Coordinator',
          priority: 'high',
          completed: false,
        },
        {
          id: 'mit-1-3',
          action: 'Book mandatory 72-hour post-discharge follow-up appointment with Endocrinology Clinic',
          responsible_role: 'Discharge Nurse Navigator',
          priority: 'medium',
          completed: true,
        },
      ],
      post_discharge_instructions: [
        'Check fingerstick blood glucose 3 times daily (fasting, pre-lunch, pre-dinner) and log in remote portal.',
        'Take newly prescribed Lantus (Glargine) 24 units subcutaneously at bedtime.',
        'Discontinue previous sulfonylurea (Glipizide) as instructed during pharmacy reconciliation.',
        'Seek immediate urgent care if blood glucose exceeds 300 mg/dL or if experiencing signs of hypoglycemia (sweating, tremors, confusion).',
      ],
    },
    isSimulated: true,
    dataSource: 'simulated_mock',
    generated_at: new Date().toISOString(),
  },
  2: {
    patient_id: 2,
    patient_name: 'Arthur Pendelton',
    medical_record_number: 'MRN-10045',
    age_group: '75-84',
    gender: 'Male',
    department: 'Cardiology',
    primary_diagnosis: 'Acute Decompensated Congestive Heart Failure (NYHA Class III)',
    admission_status: 'admitted',
    risk_category: 'high',
    readmission_probability: 0.78,
    follow_up_days: 2,
    recommendations: [
      {
        id: 'rec-2-1',
        title: 'Transition IV Diuretics to Oral Maintenance Protocol',
        category: 'medication',
        priority: 'high',
        suggested_timeframe: 'Within 24 hours',
        rationale: 'Patient achieved net negative 2.4L fluid balance with resolution of pulmonary crackles.',
        protocol_action: 'Initiate oral Torsemide 20mg daily and monitor serum potassium/creatinine at 48h.',
        status: 'accepted',
      },
      {
        id: 'rec-2-2',
        title: 'Daily Weight Tele-Monitoring & Fluid Restriction Protocol',
        category: 'monitoring',
        priority: 'high',
        suggested_timeframe: 'At discharge',
        rationale: 'Weight gain > 3 lbs in 48h is primary early warning for recurrent heart failure decompensation.',
        protocol_action: 'Provide connected digital scale and 1.8L daily fluid restriction schedule.',
        status: 'pending',
      },
    ],
    risk_drivers: [
      {
        id: 'rd-2-1',
        driver_name: 'Volume Overload Recurrence Risk',
        category: 'physiological',
        impact: 'high',
        patient_value: 'NT-proBNP 4,820 pg/mL',
        benchmark_value: '< 900 pg/mL',
        clinical_significance: 'Significantly elevated cardiac wall stress requiring aggressive neurohormonal blockade.',
        contribution_percent: 36,
      },
      {
        id: 'rd-2-2',
        driver_name: 'Reduced Left Ventricular Ejection Fraction',
        category: 'clinical',
        impact: 'high',
        patient_value: 'LVEF 32% (Echocardiogram)',
        benchmark_value: '> 50%',
        clinical_significance: 'Severely impaired cardiac output predisposes to end-organ hypoperfusion.',
        contribution_percent: 28,
      },
    ],
    discharge_plan: {
      patient_id: 2,
      ready_for_discharge: false,
      readiness_score: 66,
      target_discharge_date: 'Tomorrow afternoon',
      discharge_readiness_summary: 'Euvolemic state nearing target. Pending 24-hour oral diuretic trial stability.',
      criteria: [
        {
          id: 'crit-2-1',
          label: 'Oxygen Saturation Room Air > 94%',
          category: 'vital_signs',
          is_met: true,
          recorded_value: 'SpO2 96% on ambient air',
          required_target: '> 94% room air',
        },
        {
          id: 'crit-2-2',
          label: '24-Hour Stable Weight on Oral Diuretics',
          category: 'lab_stability',
          is_met: false,
          recorded_value: '18 hours elapsed',
          required_target: 'Full 24h stable observation',
        },
      ],
      risk_mitigation: [
        {
          id: 'mit-2-1',
          action: 'Confirm outpatient cardiology visit within 5 days',
          responsible_role: 'Nurse Navigator',
          priority: 'high',
          completed: true,
        },
      ],
      post_discharge_instructions: [
        'Weigh yourself every morning after urination before breakfast. Call clinic if weight increases by > 2 lbs in 1 day or 4 lbs in 1 week.',
        'Limit fluid intake to maximum 1.8 liters per day.',
      ],
    },
    isSimulated: true,
    dataSource: 'simulated_mock',
    generated_at: new Date().toISOString(),
  },
  3: {
    patient_id: 3,
    patient_name: 'Clara Oswald',
    medical_record_number: 'MRN-10082',
    age_group: '45-54',
    gender: 'Female',
    department: 'Internal Medicine',
    primary_diagnosis: 'Uncontrolled Type 2 Diabetes with Mild Diabetic Ketoacidosis (Resolved)',
    admission_status: 'admitted',
    risk_category: 'medium',
    readmission_probability: 0.36,
    follow_up_days: 7,
    recommendations: [
      {
        id: 'rec-3-1',
        title: 'Nutritional Consultation & Carbohydrate Counting Education',
        category: 'lifestyle',
        priority: 'medium',
        suggested_timeframe: 'Prior to discharge',
        rationale: 'Patient reported dietary inconsistency preceding current acute glycemic decompensation.',
        protocol_action: 'Arrange registered dietitian consult for customized meal planning.',
        status: 'pending',
      },
    ],
    risk_drivers: [
      {
        id: 'rd-3-1',
        driver_name: 'Recent Ketosis Resolution',
        category: 'physiological',
        impact: 'medium',
        patient_value: 'Serum Bicarbonate: 22 mEq/L',
        benchmark_value: '22 - 29 mEq/L',
        clinical_significance: 'Anion gap closed, acid-base equilibrium fully restored.',
        contribution_percent: 40,
      },
    ],
    discharge_plan: {
      patient_id: 3,
      ready_for_discharge: true,
      readiness_score: 88,
      target_discharge_date: 'Today (Approved for Discharge Review)',
      discharge_readiness_summary: 'Clinical indicators normalized. Patient ready for discharge pending final physician sign-off.',
      criteria: [
        {
          id: 'crit-3-1',
          label: 'Anion Gap Closed & Electrolytes Balanced',
          category: 'lab_stability',
          is_met: true,
          recorded_value: 'Anion Gap 8 (Normal)',
          required_target: '< 12 mEq/L',
        },
        {
          id: 'crit-3-2',
          label: 'Tolerating Regular Diet without Nausea',
          category: 'vital_signs',
          is_met: true,
          recorded_value: '3 full meals tolerated',
          required_target: 'Full oral intake',
        },
      ],
      risk_mitigation: [
        {
          id: 'mit-3-1',
          action: 'Provide 30-day insulin refill vouchers to prevent prescription lapse',
          responsible_role: 'Social Worker',
          priority: 'medium',
          completed: true,
        },
      ],
      post_discharge_instructions: [
        'Resume daily metformin 1000mg twice daily with meals.',
        'Follow up with Primary Care Physician in 7 business days.',
      ],
    },
    isSimulated: true,
    dataSource: 'simulated_mock',
    generated_at: new Date().toISOString(),
  },
};

export function generateMockClinicalSupport(
  patientId: number,
  patientName?: string,
  mrn?: string,
  primaryDiagnosis?: string,
): PatientClinicalSupportSummary {
  if (MOCK_CLINICAL_DOSSIERS[patientId]) {
    return JSON.parse(JSON.stringify(MOCK_CLINICAL_DOSSIERS[patientId]));
  }

  // Dynamic fallback for any other patient ID
  return {
    patient_id: patientId,
    patient_name: patientName || `Patient #${patientId}`,
    medical_record_number: mrn || `MRN-${(10000 + patientId).toString()}`,
    age_group: '55-64',
    gender: 'Unspecified',
    department: 'Internal Medicine',
    primary_diagnosis: primaryDiagnosis || 'Type 2 Diabetes Mellitus with Complications',
    admission_status: 'admitted',
    risk_category: 'medium',
    readmission_probability: 0.45,
    follow_up_days: 5,
    recommendations: [
      {
        id: `rec-${patientId}-1`,
        title: 'Medication Regimen Verification & Compliance Check',
        category: 'medication',
        priority: 'high',
        suggested_timeframe: 'Within 48 hours',
        rationale: 'Ensure comprehensive review of prescribed discharge medications against previous admission history.',
        protocol_action: 'Perform clinical medication reconciliation with pharmacist review.',
        status: 'pending',
      },
      {
        id: `rec-${patientId}-2`,
        title: 'Post-Encounter Follow-Up Coordination',
        category: 'follow_up',
        priority: 'medium',
        suggested_timeframe: 'At discharge',
        rationale: 'Timely outpatient touchpoints reduce 30-day readmission likelihood by up to 24%.',
        protocol_action: 'Schedule outpatient primary care appointment within 7 days of discharge.',
        status: 'pending',
      },
    ],
    risk_drivers: [
      {
        id: `rd-${patientId}-1`,
        driver_name: 'Longitudinal Disease Burden',
        category: 'clinical',
        impact: 'medium',
        patient_value: 'Chronic Metabolic Disorder',
        benchmark_value: 'Early / Managed Phase',
        clinical_significance: 'Multi-year chronic history requires continuous post-discharge care coordination.',
        contribution_percent: 50,
      },
    ],
    discharge_plan: {
      patient_id: patientId,
      ready_for_discharge: null,
      readiness_score: 72,
      target_discharge_date: 'Under Clinical Assessment',
      discharge_readiness_summary: 'Clinical discharge review in progress. Assess vital stability and outpatient follow-up availability.',
      criteria: [
        {
          id: `crit-${patientId}-1`,
          label: 'Hemodynamic Stability',
          category: 'vital_signs',
          is_met: true,
          recorded_value: 'Stable vitals 24h',
          required_target: 'Normotensive & afebrile',
        },
      ],
      risk_mitigation: [
        {
          id: `mit-${patientId}-1`,
          action: 'Confirm follow-up appointment with primary care provider',
          responsible_role: 'Discharge Coordinator',
          priority: 'medium',
          completed: false,
        },
      ],
      post_discharge_instructions: [
        'Take all medications as directed on discharge summary.',
        'Attend scheduled follow-up outpatient consultation.',
      ],
    },
    isSimulated: true,
    dataSource: 'simulated_mock',
    generated_at: new Date().toISOString(),
  };
}
