import {
  ActiveModelDetails,
  RegisteredModel,
  ModelDashboardData,
} from '@/types/model';

export const MOCK_ACTIVE_MODEL: ActiveModelDetails = {
  name: 'readmission_xgboost_v1',
  version: '1.2.0-prod',
  algorithm: 'Gradient Boosted Trees (XGBoost 2.1)',
  status: 'active',
  artifactDir: 'ml/artifacts/models/readmission_xgboost_v1',
  loadedAt: '2026-09-28T04:15:00.000Z',
  servingEndpoint: '/api/v1/risk/predict',
  latencyMs: 18,
  throughputRps: 240,
  metrics: {
    accuracy: 0.784,
    precision: 0.742,
    recall: 0.718,
    f1: 0.73,
    roc_auc: 0.826,
    specificity: 0.835,
    brier_score: 0.142,
  },
  governance: {
    framework: 'XGBoost 2.1.1 + Scikit-Learn 1.5.2',
    pythonVersion: '3.11.9',
    trainingDataset: 'Diabetes 130-US Hospitals (101,766 encounters)',
    validationSplit: 'Stratified 80/20 Train-Test with 5-Fold Cross-Validation',
    intendedUse:
      'Inpatient 30-day all-cause readmission risk scoring to assist clinical care teams in post-discharge planning.',
    fairnessAuditStatus: 'passed',
    ethicalConstraints:
      'Decision-support only. Not authorized for automated triage or discharge veto without attending physician review.',
    lastAuditedDate: '2026-09-25',
  },
  topFeatures: [
    {
      feature: 'number_inpatient',
      displayName: 'Prior Inpatient Admissions (12mo)',
      importance: 0.245,
      category: 'admission',
      description: 'Total hospitalizations recorded within the preceding 12 months.',
    },
    {
      feature: 'time_in_hospital',
      displayName: 'Length of Stay (Days)',
      importance: 0.182,
      category: 'clinical',
      description: 'Duration of current inpatient encounter in days.',
    },
    {
      feature: 'num_medications',
      displayName: 'Active Medications Count',
      importance: 0.148,
      category: 'medication',
      description: 'Count of distinct prescribed pharmaceutical agents administered.',
    },
    {
      feature: 'number_diagnoses',
      displayName: 'Total Diagnosis Codes',
      importance: 0.125,
      category: 'clinical',
      description: 'Count of primary and secondary ICD diagnosis codes entered.',
    },
    {
      feature: 'num_lab_procedures',
      displayName: 'Diagnostic Lab Procedures',
      importance: 0.104,
      category: 'clinical',
      description: 'Total laboratory diagnostic tests executed during admission.',
    },
    {
      feature: 'change_in_meds',
      displayName: 'Medication Regimen Modification',
      importance: 0.086,
      category: 'medication',
      description: 'Indicator of whether diabetes medications were adjusted or introduced.',
    },
    {
      feature: 'number_emergency',
      displayName: 'Prior Emergency Encounters',
      importance: 0.062,
      category: 'admission',
      description: 'Emergency department visits during the preceding 12 months.',
    },
    {
      feature: 'age_group',
      displayName: 'Patient Age Stratification',
      importance: 0.048,
      category: 'demographic',
      description: 'Age bracket (e.g., [70-80), [80-90)) contributing baseline demographic risk.',
    },
  ],
};

export const MOCK_REGISTERED_MODELS: RegisteredModel[] = [
  {
    id: 'mdl-001',
    name: 'readmission_xgboost_v1',
    version: '1.2.0',
    algorithm: 'XGBoost',
    task: '30-Day Readmission Risk',
    status: 'active',
    description:
      'Primary production classifier for predicting 30-day all-cause hospital readmission among diabetic inpatients.',
    trainedDate: '2026-09-28',
    datasetName: 'Diabetes 130-US Hospitals (Train Split)',
    datasetSize: 81412,
    metrics: {
      accuracy: 0.784,
      precision: 0.742,
      recall: 0.718,
      f1: 0.73,
      roc_auc: 0.826,
    },
    artifactPath: 'ml/artifacts/models/readmission_xgboost_v1.pkl',
    hyperparameters: {
      max_depth: 6,
      learning_rate: 0.05,
      n_estimators: 250,
      subsample: 0.8,
      scale_pos_weight: 1.85,
    },
  },
  {
    id: 'mdl-002',
    name: 'readmission_lightgbm_v2',
    version: '2.0.0-rc1',
    algorithm: 'LightGBM',
    task: '30-Day Readmission Risk',
    status: 'evaluating',
    description:
      'Challenger gradient-boosted model optimized for categorical feature handling and lower inference latency.',
    trainedDate: '2026-09-30',
    datasetName: 'Diabetes 130-US Hospitals (Extended 2026 Cohort)',
    datasetSize: 89200,
    metrics: {
      accuracy: 0.791,
      precision: 0.756,
      recall: 0.724,
      f1: 0.74,
      roc_auc: 0.834,
    },
    artifactPath: 'ml/artifacts/models/readmission_lightgbm_v2.pkl',
    hyperparameters: {
      num_leaves: 31,
      learning_rate: 0.03,
      n_estimators: 300,
    },
  },
  {
    id: 'mdl-003',
    name: 'readmission_randomforest_v1',
    version: '1.0.4',
    algorithm: 'Random Forest',
    task: '30-Day Readmission Risk',
    status: 'archived',
    description:
      'Ensemble forest benchmark utilized during initial milestone validation for feature importance baseline.',
    trainedDate: '2026-09-10',
    datasetName: 'Diabetes 130-US Hospitals (Train Split)',
    datasetSize: 81412,
    metrics: {
      accuracy: 0.752,
      precision: 0.708,
      recall: 0.684,
      f1: 0.696,
      roc_auc: 0.791,
    },
    artifactPath: 'ml/artifacts/models/readmission_rf_v1.pkl',
    hyperparameters: {
      n_estimators: 200,
      max_depth: 12,
      min_samples_split: 5,
    },
  },
  {
    id: 'mdl-004',
    name: 'readmission_logreg_baseline',
    version: '0.9.1',
    algorithm: 'Logistic Regression',
    task: '30-Day Readmission Risk',
    status: 'deprecated',
    description:
      'Linear baseline classifier with L2 regularization used for initial clinical odds-ratio comparisons.',
    trainedDate: '2026-08-15',
    datasetName: 'Diabetes 130-US Hospitals (Baseline)',
    datasetSize: 50000,
    metrics: {
      accuracy: 0.71,
      precision: 0.652,
      recall: 0.63,
      f1: 0.641,
      roc_auc: 0.742,
    },
    artifactPath: 'ml/artifacts/models/readmission_logreg_v0.pkl',
    hyperparameters: {
      penalty: 'l2',
      C: 1.0,
      solver: 'lbfgs',
    },
  },
  {
    id: 'mdl-005',
    name: 'los_regressor_ensemble_v1',
    version: '1.1.0',
    algorithm: 'Gradient Boosting Ensemble',
    task: 'Length of Stay Forecasting',
    status: 'active',
    description:
      'Continuous regression model predicting expected days of hospitalization to support hospital bed capacity planning.',
    trainedDate: '2026-09-22',
    datasetName: 'Diabetes 130-US Hospitals (Inpatient Cohort)',
    datasetSize: 76500,
    metrics: {
      accuracy: 0.821,
      precision: 0.794,
      recall: 0.772,
      f1: 0.783,
      roc_auc: 0.858,
    },
    artifactPath: 'ml/artifacts/models/los_ensemble_v1.pkl',
    hyperparameters: {
      n_estimators: 180,
      learning_rate: 0.04,
    },
  },
];

export function generateMockModelData(): ModelDashboardData {
  return {
    activeModel: MOCK_ACTIVE_MODEL,
    registeredModels: MOCK_REGISTERED_MODELS,
    isSimulated: true,
    dataSource: 'simulated_mock',
    lastSync: new Date().toISOString(),
  };
}
