import { DashboardStats, PatientDetail, Role, User } from '@/types';

export interface DemoUserAccount {
  user: User;
  description: string;
  defaultScope: 'assigned' | 'hospital' | 'research' | 'system';
  permissions: string[];
}

export const MOCK_USERS: Record<Role, DemoUserAccount> = {
  doctor: {
    user: {
      id: 101,
      email: 'doctor@hospital.example',
      full_name: 'Dr. Sarah Jenkins, MD',
      role: 'doctor',
      department: 'Cardiology & Internal Medicine',
      license_id: 'MD-884920',
      is_active: true,
      avatar_url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=150',
    },
    description: 'Clinical practitioner overseeing assigned patients, readmission risk alerts, and patient care pathways.',
    defaultScope: 'assigned',
    permissions: [
      'patient:read_assigned',
      'patient:write_notes',
      'prediction:read_patient',
      'alerts:manage',
    ],
  },
  hospital_admin: {
    user: {
      id: 102,
      email: 'admin@hospital.example',
      full_name: 'Michael Chang, MHA',
      role: 'hospital_admin',
      department: 'Hospital Operations & Quality Assurance',
      license_id: 'ADM-449102',
      is_active: true,
      avatar_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=150',
    },
    description: 'Executive administrator tracking hospital-wide bed occupancy, readmission penalty KPIs, and resource distribution.',
    defaultScope: 'hospital',
    permissions: [
      'patient:read_all',
      'analytics:hospital_wide',
      'reports:export_kpi',
      'department:manage',
    ],
  },
  researcher: {
    user: {
      id: 103,
      email: 'researcher@hospital.example',
      full_name: 'Dr. Elena Rostova, PhD',
      role: 'researcher',
      department: 'Clinical Data Science & Epidemiology',
      license_id: 'RES-993012',
      is_active: true,
      avatar_url: 'https://images.unsplash.com/photo-1594824813504-7422f2541991?auto=format&fit=crop&q=80&w=150',
    },
    description: 'Epidemiological researcher accessing de-identified cohort outcomes, diabetic medication effectiveness, and longitudinal data.',
    defaultScope: 'research',
    permissions: [
      'patient:read_anonymized',
      'research:export_cohort',
      'models:evaluate_fairness',
    ],
  },
  system_admin: {
    user: {
      id: 104,
      email: 'sysadmin@hospital.example',
      full_name: 'Alex Rivera',
      role: 'system_admin',
      department: 'Health Informatics & Security',
      license_id: 'SYS-110293',
      is_active: true,
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150',
    },
    description: 'IT and Compliance administrator managing RBAC governance, audit logging, model versioning, and server uptime.',
    defaultScope: 'system',
    permissions: [
      'system:manage_users',
      'system:audit_logs',
      'models:deploy',
      'security:compliance',
      'patient:read_all',
    ],
  },
};

export const MOCK_DASHBOARD_STATS: Record<Role, DashboardStats> = {
  doctor: {
    scope: 'assigned',
    total_patients: 48,
    total_admissions: 112,
    readmitted_within_30_days: 9,
    readmission_rate_percent: 8.0,
    average_length_of_stay_days: 4.2,
    high_risk_patients_count: 7,
    can_export: false,
  },
  hospital_admin: {
    scope: 'hospital',
    total_patients: 1240,
    total_admissions: 2890,
    readmitted_within_30_days: 274,
    readmission_rate_percent: 9.48,
    average_length_of_stay_days: 4.8,
    high_risk_patients_count: 182,
    bed_occupancy_percent: 86.4,
    can_export: true,
  },
  researcher: {
    scope: 'research',
    total_patients: 101766,
    total_admissions: 101766,
    readmitted_within_30_days: 11357,
    readmission_rate_percent: 11.16,
    average_length_of_stay_days: 4.39,
    high_risk_patients_count: 18450,
    active_research_cohorts: 14,
    can_export: true,
  },
  system_admin: {
    scope: 'system',
    total_patients: 1240,
    total_admissions: 2890,
    readmitted_within_30_days: 274,
    readmission_rate_percent: 9.48,
    average_length_of_stay_days: 4.8,
    high_risk_patients_count: 182,
    system_uptime_percent: 99.98,
    can_export: true,
  },
};

export const MOCK_PATIENTS: PatientDetail[] = [
  {
    id: 1,
    medical_record_number: 'MRN-104928',
    first_name: 'Arthur',
    last_name: 'Pendleton',
    full_name: 'Arthur Pendleton',
    age_group: '[70-80)',
    gender: 'Male',
    race: 'Caucasian',
    primary_diagnosis: 'Type 2 Diabetes Mellitus with Ketoacidosis (ICD-9: 250.1)',
    assigned_doctor_id: 101,
    assigned_doctor_name: 'Dr. Sarah Jenkins, MD',
    department: 'Internal Medicine',
    admission_status: 'admitted',
    risk_category: 'high',
    readmission_risk_score: 0.84,
    cohort_id: 'COHORT-A-091',
    contact_number: '+1 (555) 234-8901',
    emergency_contact: {
      name: 'Eleanor Pendleton',
      relationship: 'Spouse',
      phone: '+1 (555) 234-8902',
    },
    medical_history: {
      chronic_conditions: ['Type 2 Diabetes', 'Hypertension', 'Chronic Kidney Disease Stage 3'],
      allergies: ['Penicillin', 'Sulfa Drugs'],
      past_surgeries: ['Coronary Artery Bypass (2018)', 'Right Knee Arthroplasty (2021)'],
      family_history: ['Type 2 Diabetes (Maternal)', 'Myocardial Infarction (Paternal)'],
      primary_diagnosis: 'Diabetes Mellitus with hyperosmolar coma',
      secondary_diagnoses: ['Essential Hypertension (401.9)', 'Congestive Heart Failure (428.0)'],
      smoking_status: 'Former Smoker (Quit 2015)',
      bmi: 31.4,
    },
    admissions: [
      {
        id: 501,
        admission_date: '2026-08-28',
        discharge_date: null,
        time_in_hospital: 6,
        admission_type: 'Emergency',
        discharge_disposition: 'Currently Inpatient',
        num_medications: 18,
        number_diagnoses: 9,
        num_lab_procedures: 64,
        num_procedures: 2,
        primary_diagnosis: 'Diabetic Ketoacidosis (250.1)',
        readmitted: 'NO',
        readmitted_within_30: false,
        attending_physician: 'Dr. Sarah Jenkins, MD',
        department: 'Intensive Care / Internal Medicine',
      },
      {
        id: 488,
        admission_date: '2026-07-10',
        discharge_date: '2026-07-15',
        time_in_hospital: 5,
        admission_type: 'Urgent',
        discharge_disposition: 'Discharged to Home with Home Health Service',
        num_medications: 14,
        number_diagnoses: 7,
        num_lab_procedures: 48,
        num_procedures: 1,
        primary_diagnosis: 'Uncontrolled Hyperglycemia (250.02)',
        readmitted: '>30',
        readmitted_within_30: false,
        attending_physician: 'Dr. Robert Vance, MD',
        department: 'Internal Medicine',
      },
    ],
    treatment: {
      current_medications: [
        {
          name: 'Insulin Glargine (Lantus)',
          dosage: '24 Units',
          frequency: 'Subcutaneously Once Daily at Bedtime',
          route: 'Subcutaneous',
          prescribed_date: '2026-08-28',
          status: 'active',
        },
        {
          name: 'Metformin Hydrochloride',
          dosage: '1000 mg',
          frequency: 'Twice Daily with Meals',
          route: 'Oral',
          prescribed_date: '2026-08-28',
          status: 'active',
        },
        {
          name: 'Lisinopril',
          dosage: '20 mg',
          frequency: 'Once Daily',
          route: 'Oral',
          prescribed_date: '2026-08-28',
          status: 'active',
        },
        {
          name: 'Atorvastatin',
          dosage: '40 mg',
          frequency: 'Once Daily at Bedtime',
          route: 'Oral',
          prescribed_date: '2026-08-28',
          status: 'active',
        },
      ],
      lab_results: [
        {
          test_name: 'HbA1c Glycated Hemoglobin',
          value: '10.4%',
          reference_range: '< 5.7%',
          status: 'critical',
          date: '2026-08-29',
        },
        {
          test_name: 'Fasting Blood Glucose',
          value: '268 mg/dL',
          reference_range: '70 - 99 mg/dL',
          status: 'critical',
          date: '2026-09-02',
        },
        {
          test_name: 'Serum Creatinine',
          value: '1.6 mg/dL',
          reference_range: '0.7 - 1.3 mg/dL',
          status: 'abnormal',
          date: '2026-09-01',
        },
        {
          test_name: 'eGFR',
          value: '44 mL/min/1.73m²',
          reference_range: '> 60 mL/min',
          status: 'abnormal',
          date: '2026-09-01',
        },
      ],
      care_plan: [
        'Continuous sliding scale insulin protocol with hourly capillary blood glucose monitoring.',
        'Nephrology consult regarding renal dosage adjustments for ACE inhibitors.',
        'Structured diabetes nurse educator discharge counseling and post-discharge telehealth check-in.',
      ],
      dietary_restrictions: ['Consistent Carbohydrate Diet (60g/meal)', 'Low Sodium (<2g/day)'],
      follow_up_instructions: 'Follow-up appointment with Endocrinology scheduled within 7 days of discharge. Patient will transmit daily glucometer logs.',
    },
  },
  {
    id: 2,
    medical_record_number: 'MRN-209841',
    first_name: 'Maria',
    last_name: 'Santos-Cruz',
    full_name: 'Maria Santos-Cruz',
    age_group: '[50-60)',
    gender: 'Female',
    race: 'Hispanic',
    primary_diagnosis: 'Congestive Heart Failure, Unspecified (ICD-9: 428.0)',
    assigned_doctor_id: 101,
    assigned_doctor_name: 'Dr. Sarah Jenkins, MD',
    department: 'Cardiology',
    admission_status: 'admitted',
    risk_category: 'high',
    readmission_risk_score: 0.78,
    cohort_id: 'COHORT-A-092',
    contact_number: '+1 (555) 489-1122',
    emergency_contact: {
      name: 'Carlos Cruz',
      relationship: 'Son',
      phone: '+1 (555) 489-1123',
    },
    medical_history: {
      chronic_conditions: ['Heart Failure with Reduced Ejection Fraction (EF 30%)', 'Type 2 Diabetes', 'Dyslipidemia'],
      allergies: ['Aspirin (Bronchospasm)'],
      past_surgeries: ['Cardiac Catheterization (2023)'],
      family_history: ['Cardiomyopathy (Father)'],
      primary_diagnosis: 'Congestive Heart Failure Exacerbation',
      secondary_diagnoses: ['Type 2 Diabetes (250.00)', 'Hypertensive Heart Disease (402.90)'],
      smoking_status: 'Never Smoked',
      bmi: 28.2,
    },
    admissions: [
      {
        id: 502,
        admission_date: '2026-08-30',
        discharge_date: null,
        time_in_hospital: 4,
        admission_type: 'Emergency',
        discharge_disposition: 'Currently Inpatient',
        num_medications: 15,
        number_diagnoses: 8,
        num_lab_procedures: 52,
        num_procedures: 1,
        primary_diagnosis: 'Acute on Chronic Systolic Heart Failure (428.23)',
        readmitted: '<30',
        readmitted_within_30: true,
        attending_physician: 'Dr. Sarah Jenkins, MD',
        department: 'Cardiology',
      },
    ],
    treatment: {
      current_medications: [
        {
          name: 'Furosemide (Lasix)',
          dosage: '40 mg IV',
          frequency: 'Twice Daily',
          route: 'Intravenous',
          prescribed_date: '2026-08-30',
          status: 'active',
        },
        {
          name: 'Sacubitril/Valsartan (Entresto)',
          dosage: '24/26 mg',
          frequency: 'Twice Daily',
          route: 'Oral',
          prescribed_date: '2026-08-30',
          status: 'active',
        },
        {
          name: 'Empagliflozin (Jardiance)',
          dosage: '10 mg',
          frequency: 'Once Daily',
          route: 'Oral',
          prescribed_date: '2026-08-30',
          status: 'active',
        },
      ],
      lab_results: [
        {
          test_name: 'NT-proBNP',
          value: '4,850 pg/mL',
          reference_range: '< 125 pg/mL',
          status: 'critical',
          date: '2026-08-30',
        },
        {
          test_name: 'Serum Potassium',
          value: '4.2 mEq/L',
          reference_range: '3.5 - 5.0 mEq/L',
          status: 'normal',
          date: '2026-09-02',
        },
      ],
      care_plan: [
        'Aggressive IV diuresis targeting 1.5-2L negative fluid balance daily.',
        'Strict daily standing weight before breakfast and fluid restriction (1.5L/day).',
        'Heart failure transition nurse navigator assigned for 30-day post-discharge monitoring.',
      ],
      dietary_restrictions: ['Sodium restricted (< 1500mg/day)', 'Fluid restriction (1500mL/day)'],
      follow_up_instructions: 'Cardiology outpatient clinic visit in 5 business days with repeat basic metabolic panel.',
    },
  },
  {
    id: 3,
    medical_record_number: 'MRN-334190',
    first_name: 'James',
    last_name: 'Washington',
    full_name: 'James Washington',
    age_group: '[60-70)',
    gender: 'Male',
    race: 'AfricanAmerican',
    primary_diagnosis: 'Chronic Obstructive Pulmonary Disease with Acute Exacerbation (ICD-9: 491.21)',
    assigned_doctor_id: 101,
    assigned_doctor_name: 'Dr. Sarah Jenkins, MD',
    department: 'Pulmonology',
    admission_status: 'admitted',
    risk_category: 'medium',
    readmission_risk_score: 0.46,
    cohort_id: 'COHORT-B-114',
    contact_number: '+1 (555) 782-9900',
    emergency_contact: {
      name: 'Tanya Washington',
      relationship: 'Daughter',
      phone: '+1 (555) 782-9901',
    },
    medical_history: {
      chronic_conditions: ['Severe COPD (GOLD Stage 3)', 'Type 2 Diabetes Mellitus', 'Peripheral Vascular Disease'],
      allergies: ['Codeine (Nausea/Vomiting)'],
      past_surgeries: ['Appendectomy (1995)'],
      family_history: ['Emphysema (Father)'],
      primary_diagnosis: 'COPD Exacerbation',
      secondary_diagnoses: ['Diabetes without Mention of Complication (250.00)', 'Tobacco Use Disorder (305.1)'],
      smoking_status: 'Current Every Day Smoker (40 pack-years)',
      bmi: 24.5,
    },
    admissions: [
      {
        id: 503,
        admission_date: '2026-09-01',
        discharge_date: null,
        time_in_hospital: 2,
        admission_type: 'Emergency',
        discharge_disposition: 'Currently Inpatient',
        num_medications: 12,
        number_diagnoses: 6,
        num_lab_procedures: 38,
        num_procedures: 1,
        primary_diagnosis: 'Obstructive Chronic Bronchitis with Acute Exacerbation (491.21)',
        readmitted: 'NO',
        readmitted_within_30: false,
        attending_physician: 'Dr. Sarah Jenkins, MD',
        department: 'Pulmonology',
      },
    ],
    treatment: {
      current_medications: [
        {
          name: 'Prednisone',
          dosage: '40 mg',
          frequency: 'Once Daily for 5 days',
          route: 'Oral',
          prescribed_date: '2026-09-01',
          status: 'active',
        },
        {
          name: 'Ipratropium / Albuterol (DuoNeb)',
          dosage: '0.5mg / 2.5mg',
          frequency: 'Every 4 hours PRN',
          route: 'Nebulized Inhalation',
          prescribed_date: '2026-09-01',
          status: 'active',
        },
      ],
      lab_results: [
        {
          test_name: 'Arterial Blood Gas pH',
          value: '7.34',
          reference_range: '7.35 - 7.45',
          status: 'abnormal',
          date: '2026-09-01',
        },
        {
          test_name: 'PaCO2',
          value: '48 mmHg',
          reference_range: '35 - 45 mmHg',
          status: 'abnormal',
          date: '2026-09-01',
        },
      ],
      care_plan: [
        'Nebulizer treatments and supplemental oxygen titrated to keep SpO2 88-92%.',
        'Smoking cessation inpatient consult and behavioral intervention.',
        'Pulmonary rehab referral upon discharge.',
      ],
      dietary_restrictions: ['High Protein, High Calorie as tolerated'],
      follow_up_instructions: 'Pulmonology clinic visit in 10-14 days. Spirometry re-evaluation in 6 weeks.',
    },
  },
  {
    id: 4,
    medical_record_number: 'MRN-449102',
    first_name: 'Linda',
    last_name: 'Kowalski',
    full_name: 'Linda Kowalski',
    age_group: '[40-50)',
    gender: 'Female',
    race: 'Caucasian',
    primary_diagnosis: 'Acute Pyelonephritis (ICD-9: 590.10)',
    assigned_doctor_id: 101,
    assigned_doctor_name: 'Dr. Sarah Jenkins, MD',
    department: 'Internal Medicine',
    admission_status: 'discharged',
    risk_category: 'low',
    readmission_risk_score: 0.12,
    cohort_id: 'COHORT-C-201',
    contact_number: '+1 (555) 901-3344',
    emergency_contact: {
      name: 'David Kowalski',
      relationship: 'Husband',
      phone: '+1 (555) 901-3345',
    },
    medical_history: {
      chronic_conditions: ['Type 2 Diabetes (Well-controlled, HbA1c 6.4%)'],
      allergies: ['No Known Drug Allergies (NKDA)'],
      past_surgeries: ['Cesarean Section (2012)'],
      family_history: ['Hypertension (Mother)'],
      primary_diagnosis: 'Acute Pyelonephritis',
      secondary_diagnoses: ['Diabetes without mention of complication (250.00)'],
      smoking_status: 'Never Smoker',
      bmi: 26.8,
    },
    admissions: [
      {
        id: 495,
        admission_date: '2026-08-20',
        discharge_date: '2026-08-23',
        time_in_hospital: 3,
        admission_type: 'Urgent',
        discharge_disposition: 'Discharged to Home or Self Care',
        num_medications: 6,
        number_diagnoses: 3,
        num_lab_procedures: 28,
        num_procedures: 0,
        primary_diagnosis: 'Acute Pyelonephritis (590.10)',
        readmitted: 'NO',
        readmitted_within_30: false,
        attending_physician: 'Dr. Sarah Jenkins, MD',
        department: 'Internal Medicine',
      },
    ],
    treatment: {
      current_medications: [
        {
          name: 'Ciprofloxacin',
          dosage: '500 mg',
          frequency: 'Twice Daily to complete 10-day course',
          route: 'Oral',
          prescribed_date: '2026-08-23',
          status: 'completed',
        },
      ],
      lab_results: [
        {
          test_name: 'WBC Count',
          value: '7.8 x10^3/uL',
          reference_range: '4.5 - 11.0 x10^3/uL',
          status: 'normal',
          date: '2026-08-23',
        },
      ],
      care_plan: ['Completed 3 days IV Ceftriaxone, transitioned to oral Cipro.'],
      dietary_restrictions: ['High fluid hydration'],
      follow_up_instructions: 'Primary care follow up in 2 weeks.',
    },
  },
  {
    id: 5,
    medical_record_number: 'MRN-558291',
    first_name: 'Devon',
    last_name: 'Brooks',
    full_name: 'Devon Brooks',
    age_group: '[60-70)',
    gender: 'Male',
    race: 'AfricanAmerican',
    primary_diagnosis: 'Acute Myocardial Infarction, Inferior Wall (ICD-9: 410.41)',
    assigned_doctor_id: 101,
    assigned_doctor_name: 'Dr. Sarah Jenkins, MD',
    department: 'Cardiology',
    admission_status: 'admitted',
    risk_category: 'high',
    readmission_risk_score: 0.72,
    cohort_id: 'COHORT-A-093',
    contact_number: '+1 (555) 678-1290',
    emergency_contact: {
      name: 'Maya Brooks',
      relationship: 'Spouse',
      phone: '+1 (555) 678-1291',
    },
    medical_history: {
      chronic_conditions: ['Coronary Artery Disease', 'Hyperlipidemia', 'Type 2 Diabetes', 'Hypertension'],
      allergies: ['Morphine (Rash)'],
      past_surgeries: ['Percutaneous Coronary Intervention with Stent (2026)'],
      family_history: ['Early CAD (Brother at age 48)'],
      primary_diagnosis: 'STEMI Inferior Wall',
      secondary_diagnoses: ['Hypercholesterolemia (272.0)', 'Essential Hypertension (401.9)'],
      smoking_status: 'Former Smoker',
      bmi: 29.1,
    },
    admissions: [
      {
        id: 504,
        admission_date: '2026-08-31',
        discharge_date: null,
        time_in_hospital: 3,
        admission_type: 'Emergency',
        discharge_disposition: 'Currently Inpatient',
        num_medications: 16,
        number_diagnoses: 7,
        num_lab_procedures: 44,
        num_procedures: 2,
        primary_diagnosis: 'Acute Inferior Myocardial Infarction (410.41)',
        readmitted: 'NO',
        readmitted_within_30: false,
        attending_physician: 'Dr. Sarah Jenkins, MD',
        department: 'Cardiology / Cath Lab',
      },
    ],
    treatment: {
      current_medications: [
        {
          name: 'Ticagrelor (Brilinta)',
          dosage: '90 mg',
          frequency: 'Twice Daily',
          route: 'Oral',
          prescribed_date: '2026-08-31',
          status: 'active',
        },
        {
          name: 'Aspirin',
          dosage: '81 mg',
          frequency: 'Once Daily',
          route: 'Oral',
          prescribed_date: '2026-08-31',
          status: 'active',
        },
        {
          name: 'Metoprolol Succinate',
          dosage: '50 mg',
          frequency: 'Once Daily',
          route: 'Oral',
          prescribed_date: '2026-08-31',
          status: 'active',
        },
      ],
      lab_results: [
        {
          test_name: 'Troponin I High Sensitivity',
          value: '1,420 ng/L',
          reference_range: '< 14 ng/L',
          status: 'critical',
          date: '2026-08-31',
        },
      ],
      care_plan: [
        'Post-PCI care following successful drug-eluting stent placement to RCA.',
        'Cardiac rehabilitation phase 1 in-hospital protocol initiated.',
        'Enrollment in 30-day post-MI telehealth monitoring program.',
      ],
      dietary_restrictions: ['Heart-Healthy Mediterranean Diet', 'Low Sodium (<2000mg/day)'],
      follow_up_instructions: 'Cardiology outpatient appointment in 1 week with post-MI echo scheduled at 6 weeks.',
    },
  },
  {
    id: 6,
    medical_record_number: 'MRN-672910',
    first_name: 'Grace',
    last_name: 'Liu',
    full_name: 'Grace Liu',
    age_group: '[30-40)',
    gender: 'Female',
    race: 'Asian',
    primary_diagnosis: 'Gestational Diabetes Mellitus (ICD-9: 648.83)',
    assigned_doctor_id: 101,
    assigned_doctor_name: 'Dr. Sarah Jenkins, MD',
    department: 'Obstetrics / Endocrinology',
    admission_status: 'discharged',
    risk_category: 'low',
    readmission_risk_score: 0.08,
    cohort_id: 'COHORT-C-202',
    contact_number: '+1 (555) 345-6789',
    emergency_contact: {
      name: 'Kenji Liu',
      relationship: 'Spouse',
      phone: '+1 (555) 345-6790',
    },
    medical_history: {
      chronic_conditions: ['Gestational Diabetes'],
      allergies: ['No Known Drug Allergies (NKDA)'],
      past_surgeries: ['None'],
      family_history: ['Type 2 Diabetes (Mother)'],
      primary_diagnosis: 'Gestational Diabetes Mellitus',
      secondary_diagnoses: ['Normal Pregnancy, Third Trimester (V22.2)'],
      smoking_status: 'Never Smoker',
      bmi: 23.4,
    },
    admissions: [
      {
        id: 480,
        admission_date: '2026-08-10',
        discharge_date: '2026-08-12',
        time_in_hospital: 2,
        admission_type: 'Elective',
        discharge_disposition: 'Discharged to Home or Self Care',
        num_medications: 4,
        number_diagnoses: 2,
        num_lab_procedures: 22,
        num_procedures: 0,
        primary_diagnosis: 'Abnormal Glucose Tolerance of Pregnancy (648.83)',
        readmitted: 'NO',
        readmitted_within_30: false,
        attending_physician: 'Dr. Sarah Jenkins, MD',
        department: 'Obstetrics',
      },
    ],
    treatment: {
      current_medications: [
        {
          name: 'Insulin Lispro (Humalog)',
          dosage: '4 Units before meals',
          frequency: 'Three Times Daily with Meals',
          route: 'Subcutaneous',
          prescribed_date: '2026-08-11',
          status: 'active',
        },
      ],
      lab_results: [
        {
          test_name: '3-Hour Oral Glucose Tolerance Test (OGTT)',
          value: '185 mg/dL (2-hr)',
          reference_range: '< 140 mg/dL',
          status: 'abnormal',
          date: '2026-08-10',
        },
      ],
      care_plan: ['Nutritional counseling and 4x daily glucometer tracking.'],
      dietary_restrictions: ['Gestational Diabetic Meal Plan'],
      follow_up_instructions: 'Weekly OB/Gyn and MFM clinic follow-up.',
    },
  },
];
