"""initial schema

Revision ID: 5319456fa247
Revises: 
Create Date: 2026-09-16 15:53:52.087234
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5319456fa247'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_admissions_patient', table_name='admissions')
    op.create_index(op.f('ix_admissions_id'), 'admissions', ['id'], unique=False)
    op.create_index(op.f('ix_admissions_patient_id'), 'admissions', ['patient_id'], unique=False)
    op.drop_constraint('admissions_patient_id_fkey', 'admissions', type_='foreignkey')
    op.create_foreign_key(None, 'admissions', 'patients', ['patient_id'], ['id'])
    op.drop_index('idx_audit_actor_created', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.drop_index('idx_patients_assigned_doctor', table_name='patients')
    op.drop_constraint('patients_medical_record_number_key', 'patients', type_='unique')
    op.create_index(op.f('ix_patients_assigned_doctor_id'), 'patients', ['assigned_doctor_id'], unique=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_medical_record_number'), 'patients', ['medical_record_number'], unique=True)
    op.drop_constraint('patients_assigned_doctor_id_fkey', 'patients', type_='foreignkey')
    op.drop_index('idx_risk_patient_created', table_name='risk_predictions')
    op.create_index(op.f('ix_risk_predictions_id'), 'risk_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_risk_predictions_patient_id'), 'risk_predictions', ['patient_id'], unique=False)
    op.drop_constraint('risk_predictions_patient_id_fkey', 'risk_predictions', type_='foreignkey')
    op.drop_constraint('risk_predictions_admission_id_fkey', 'risk_predictions', type_='foreignkey')
    op.create_foreign_key(None, 'risk_predictions', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(None, 'risk_predictions', 'admissions', ['admission_id'], ['id'])
    op.drop_index('idx_treatment_admission', table_name='treatment_outcomes')
    op.create_index(op.f('ix_treatment_outcomes_admission_id'), 'treatment_outcomes', ['admission_id'], unique=False)
    op.create_index(op.f('ix_treatment_outcomes_id'), 'treatment_outcomes', ['id'], unique=False)
    op.drop_constraint('treatment_outcomes_admission_id_fkey', 'treatment_outcomes', type_='foreignkey')
    op.create_foreign_key(None, 'treatment_outcomes', 'admissions', ['admission_id'], ['id'])
    op.drop_index('idx_users_role', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.drop_constraint(None, 'treatment_outcomes', type_='foreignkey')
    op.create_foreign_key('treatment_outcomes_admission_id_fkey', 'treatment_outcomes', 'admissions', ['admission_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_treatment_outcomes_id'), table_name='treatment_outcomes')
    op.drop_index(op.f('ix_treatment_outcomes_admission_id'), table_name='treatment_outcomes')
    op.create_index('idx_treatment_admission', 'treatment_outcomes', ['admission_id'], unique=False)
    op.drop_constraint(None, 'risk_predictions', type_='foreignkey')
    op.drop_constraint(None, 'risk_predictions', type_='foreignkey')
    op.create_foreign_key('risk_predictions_admission_id_fkey', 'risk_predictions', 'admissions', ['admission_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('risk_predictions_patient_id_fkey', 'risk_predictions', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_risk_predictions_patient_id'), table_name='risk_predictions')
    op.drop_index(op.f('ix_risk_predictions_id'), table_name='risk_predictions')
    op.create_index('idx_risk_patient_created', 'risk_predictions', ['patient_id', sa.text('created_at DESC')], unique=False)
    op.create_foreign_key('patients_assigned_doctor_id_fkey', 'patients', 'users', ['assigned_doctor_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_patients_medical_record_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_assigned_doctor_id'), table_name='patients')
    op.create_unique_constraint('patients_medical_record_number_key', 'patients', ['medical_record_number'])
    op.create_index('idx_patients_assigned_doctor', 'patients', ['assigned_doctor_id'], unique=False)
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.create_index('idx_audit_actor_created', 'audit_logs', ['actor_id', sa.text('created_at DESC')], unique=False)
    op.drop_constraint(None, 'admissions', type_='foreignkey')
    op.create_foreign_key('admissions_patient_id_fkey', 'admissions', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_admissions_patient_id'), table_name='admissions')
    op.drop_index(op.f('ix_admissions_id'), table_name='admissions')
    op.create_index('idx_admissions_patient', 'admissions', ['patient_id'], unique=False)
    # ### end Alembic commands ###
