'use client';
import { useEffect,useMemo,useState } from 'react';
import { Download,Microscope,ShieldCheck } from 'lucide-react';
import { useAuth } from '@/lib/auth-context'; import { apiFetch } from '@/lib/api'; import { P } from '@/lib/permissions'; import type { AnonymisedPatient } from '@/types';
import { EmptyState,ErrorState,KpiCard,PageHeader,RiskPill,SectionCard,TableSkeleton,SuccessNotice } from '@/components/ui';

function csvCell(value:unknown){const text=String(value??'');return /[",\n]/.test(text)?`"${text.replace(/"/g,'""')}"`:text}
function downloadText(filename:string,text:string,mime='text/csv;charset=utf-8'){const blob=new Blob([text],{type:mime});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}

export default function Research(){
 const {token,permissions}=useAuth();const [rows,setRows]=useState<AnonymisedPatient[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [downloading,setDownloading]=useState(false);const [success,setSuccess]=useState('');const allowed=permissions.includes(P.patientAnon);const canExport=permissions.includes(P.researchExport);
 useEffect(()=>{if(!token||!allowed){setLoading(false);return}setLoading(true);apiFetch<AnonymisedPatient[]>('/patients/anonymised',{},token).then(setRows).catch(e=>setError(e?.message??'Could not load cohort.')).finally(()=>setLoading(false))},[token,allowed]);
 const counts=useMemo(()=>rows.reduce((a,r)=>{const key=r.risk_category as keyof typeof a;if(key in a)a[key]++;return a},{low:0,medium:0,high:0,not_scored:0}),[rows]);
 function download(){if(!canExport||!rows.length)return;setDownloading(true);setError('');setSuccess('');try{const header=['Pseudo ID','Age group','Gender','Primary diagnosis','Risk category'];const body=rows.map(r=>[r.pseudo_id,r.age_group,r.gender,r.primary_diagnosis,r.risk_category].map(csvCell).join(','));downloadText('healthforecast_research_cohort.csv',[header.join(','),...body].join('\n'));setSuccess(`Exported ${rows.length} anonymised cohort records.`)}catch{setError('Could not create the anonymised research export.')}finally{setDownloading(false)}}
 if(!allowed)return <div><PageHeader eyebrow="Research" title="Research cohort" description="This workspace is restricted to de-identified cohort access."/><SectionCard><EmptyState title="Research access required" message="No patient identifiers are exposed here. Use an account with patient:read_anonymized to access the cohort." icon={<ShieldCheck className="h-5 w-5"/>}/></SectionCard></div>;
 return <div><PageHeader eyebrow="Research" title="De-identified cohort" description="Research-facing patient data returned by /patients/anonymised. Names, MRNs, real IDs and assigned doctors are not rendered." actions={canExport?<button onClick={download} disabled={downloading||loading||rows.length===0} className="btn-secondary"><Download className="h-4 w-4"/>{downloading?'Preparing…':'Export anonymised cohort'}</button>:undefined}/>{error&&<div className="mb-5"><ErrorState message={error}/></div>}{success&&<div className="mb-5"><SuccessNotice message={success}/></div>}
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Cohort size" value={loading?'—':rows.length} icon={<Microscope className="h-5 w-5"/>}/><KpiCard label="High risk" value={counts.high} accent="red"/><KpiCard label="Medium risk" value={counts.medium} accent="amber"/><KpiCard label="Low risk" value={counts.low} accent="green"/></div>
 <SectionCard title="Research export" description="The export contains only fields returned by the anonymised endpoint and is generated locally in the browser." className="mt-6"><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-700">Included</p><p className="mt-1 text-xs leading-5 text-slate-500">Pseudo ID, age group, gender, diagnosis and risk category.</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold text-slate-700">Excluded</p><p className="mt-1 text-xs leading-5 text-slate-500">Names, MRNs, real patient IDs and assigned doctors.</p></div><div className="rounded-xl bg-cyan-50 p-4"><p className="text-xs font-semibold text-clinical-700">Format</p><p className="mt-1 text-xs leading-5 text-slate-600">CSV for research workflows and spreadsheet analysis.</p></div></div>{!canExport&&<p className="mt-4 text-xs text-slate-500">Your account can view the cohort but does not have research_dataset:export.</p>}</SectionCard>
 <SectionCard title="Research cohort" description="Only fields explicitly returned by the anonymised backend contract are displayed." className="mt-6">{loading?<TableSkeleton columns={5} rows={7}/>:rows.length===0?<EmptyState title="No cohort records" message="The anonymised endpoint returned no records."/>:<div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b border-slate-100 text-[11px] font-bold uppercase tracking-wide text-slate-400"><th className="pb-3">Pseudo ID</th><th className="pb-3">Age group</th><th className="pb-3">Gender</th><th className="pb-3">Diagnosis</th><th className="pb-3">Risk</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(r=><tr key={r.pseudo_id}><td className="py-3 font-mono text-xs font-semibold">{r.pseudo_id}</td><td className="py-3">{r.age_group??'—'}</td><td className="py-3">{r.gender??'—'}</td><td className="py-3">{r.primary_diagnosis??'—'}</td><td className="py-3"><RiskPill category={r.risk_category}/></td></tr>)}</tbody></table></div>}</SectionCard></div>
}
